"""End-to-end-ish tests of each workflow stage, using fakes for collaborators."""

from __future__ import annotations

import json

import pytest

from aidlc import db
from aidlc.workflows import (
    run_idea_to_spec,
    run_spec_to_tasks,
    run_status_updates,
    run_task_to_code,
)
from tests.fakes import FakeGitHub, FakeLLM, FakeOpenProject

# ---------- Stage 1: idea → spec -------------------------------------------


class TestIdeaToSpec:
    def _spec_response(self) -> str:
        return json.dumps(
            {
                "summary": "Accountants need CSV export of invoices.",
                "user_story": "As an accountant, I want to export invoices, so that I can audit them.",
                "acceptance_criteria": [
                    "GET /api/invoices.csv returns 200 with valid CSV",
                    "Export includes all invoices from selected date range",
                ],
                "out_of_scope": ["PDF export"],
                "risks": ["Large exports could OOM the web worker"],
                "open_questions": ["What date filters are required?"],
                "rough_size": "M",
            }
        )

    def test_writes_spec_to_description_and_transitions_status(self) -> None:
        op = FakeOpenProject()
        wp = op.add_wp(subject="Export invoices", description="accountants want CSV")
        llm = FakeLLM(responses=[self._spec_response()])

        result = run_idea_to_spec(llm=llm, op=op, work_package_id=wp.id)

        assert result.transitioned_to == "Specified"
        stored = op.get_work_package(wp.id)
        assert "## Spec (generated by AI-DLC)" in (stored.description_text or "")
        assert "accountants want CSV" in (stored.description_text or ""), (
            "original idea should be preserved under a separator"
        )
        assert stored.status_name == "Specified"
        assert len(op.comments) == 1

    def test_skips_when_already_run_unless_forced(self) -> None:
        op = FakeOpenProject()
        wp = op.add_wp(subject="x")
        llm = FakeLLM(responses=[self._spec_response(), self._spec_response()])

        run_idea_to_spec(llm=llm, op=op, work_package_id=wp.id)
        assert db.has_run("idea_to_spec", wp.id)

        # Second call without force should NOT call the LLM again
        run_idea_to_spec(llm=llm, op=op, work_package_id=wp.id)
        assert len(llm.responses) == 1  # first still unused

        # With force, it runs again
        run_idea_to_spec(llm=llm, op=op, work_package_id=wp.id, force=True)
        assert len(llm.responses) == 0

    def test_records_error_run_on_unparseable_output(self) -> None:
        op = FakeOpenProject()
        wp = op.add_wp(subject="bad output")
        llm = FakeLLM(responses=["no json here at all"])
        with pytest.raises(ValueError):
            run_idea_to_spec(llm=llm, op=op, work_package_id=wp.id)
        assert not db.has_run("idea_to_spec", wp.id)  # not an "ok" run


# ---------- Stage 2: spec → tasks ------------------------------------------


class TestSpecToTasks:
    SPEC_MARKDOWN = (
        "## Spec (generated by AI-DLC)\n\n"
        "**Summary:** CSV export.\n\n"
        "### Acceptance criteria\n"
        "- Endpoint returns CSV\n"
        "- Supports date range\n\n"
        "### Risks\n"
        "- OOM on large exports\n"
    )

    def _tasks_response(self) -> str:
        return json.dumps(
            [
                {
                    "subject": "Add GET /api/invoices.csv endpoint",
                    "type": "Task",
                    "description": "...\n## Definition of done\nReturns CSV.",
                    "depends_on_index": [],
                },
                {
                    "subject": "Add date-range filter to CSV export",
                    "type": "Task",
                    "description": "...\n## Definition of done\nQuery params honoured.",
                    "depends_on_index": [0],
                },
            ]
        )

    def test_creates_child_tasks_with_parent_link(self) -> None:
        op = FakeOpenProject()
        parent = op.add_wp(subject="CSV export", description=self.SPEC_MARKDOWN)
        llm = FakeLLM(responses=[self._tasks_response()])

        result = run_spec_to_tasks(
            llm=llm, op=op, parent_work_package_id=parent.id, project_identifier="ai-dlc-demo"
        )

        assert len(result.created_task_ids) == 2
        for child_id in result.created_task_ids:
            child = op.get_work_package(child_id)
            assert child.parent_id == parent.id
            assert child.type_name == "Task"
        # Dependencies annotated in description
        second = op.get_work_package(result.created_task_ids[1])
        assert "Depends on" in (second.description_text or "")

    def test_rejects_non_array_output(self) -> None:
        op = FakeOpenProject()
        parent = op.add_wp(subject="x", description=self.SPEC_MARKDOWN)
        llm = FakeLLM(responses=['{"not": "a list"}'])
        with pytest.raises(ValueError, match="tasks"):
            run_spec_to_tasks(
                llm=llm, op=op, parent_work_package_id=parent.id, project_identifier="demo"
            )

    def test_falls_back_to_default_type_when_unknown(self) -> None:
        op = FakeOpenProject()
        parent = op.add_wp(subject="x", description=self.SPEC_MARKDOWN)
        llm = FakeLLM(
            responses=[
                json.dumps(
                    [
                        {
                            "subject": "Do thing",
                            "type": "NonexistentType",
                            "description": "...",
                            "depends_on_index": [],
                        }
                    ]
                )
            ]
        )
        result = run_spec_to_tasks(
            llm=llm, op=op, parent_work_package_id=parent.id, project_identifier="demo"
        )
        child = op.get_work_package(result.created_task_ids[0])
        assert child.type_name == "Task"  # fell back to default


# ---------- Stage 3: task → code -------------------------------------------


class TestTaskToCode:
    def _code_response(self) -> str:
        return json.dumps(
            {
                "branch_name": "feat/csv export",  # has a space on purpose
                "commit_message": "feat: scaffold invoices CSV endpoint",
                "pr_title": "[WP] Scaffold invoices CSV endpoint",
                "pr_body": "scaffold only\n## What this does not do\n- date filter",
                "files": [
                    {
                        "path": "app/routes/invoices_csv.py",
                        "content": "def handler(): raise NotImplementedError\n",
                    },
                    {
                        "path": "tests/test_invoices_csv.py",
                        "content": "def test_placeholder():\n    assert False\n",
                    },
                ],
            }
        )

    def test_opens_draft_pr_and_links_back(self) -> None:
        op = FakeOpenProject()
        task = op.add_wp(subject="Scaffold CSV endpoint", type_name="Task")
        gh = FakeGitHub()
        llm = FakeLLM(responses=[self._code_response()])

        result = run_task_to_code(
            llm=llm,
            op=op,
            gh=gh,
            work_package_id=task.id,
            repo="acme/repo",
            base_branch="main",
        )

        assert result.branch.startswith("aidlc/")
        assert " " not in result.branch, "branch name must be sanitized"
        assert result.pr_number in gh.prs
        assert (result.branch, "app/routes/invoices_csv.py") in gh.files
        assert (result.branch, "tests/test_invoices_csv.py") in gh.files
        # Snapshot recorded for stage 4
        snap = db.get_snapshot(task.id)
        assert snap is not None
        assert snap.pr_number == result.pr_number
        # Comment linking PR back to WP
        assert any("pull/" in body for _, body in op.comments)

    def test_rejects_empty_file_list(self) -> None:
        op = FakeOpenProject()
        task = op.add_wp(subject="x", type_name="Task")
        gh = FakeGitHub()
        llm = FakeLLM(
            responses=[
                json.dumps({"branch_name": "feat/x", "files": [], "pr_title": "t", "pr_body": "b"})
            ]
        )
        with pytest.raises(ValueError, match="no files"):
            run_task_to_code(
                llm=llm, op=op, gh=gh, work_package_id=task.id, repo="acme/repo", base_branch="main"
            )


# ---------- Stage 4: status updates ----------------------------------------


class TestStatusUpdates:
    def _setup_open_pr(self) -> tuple[FakeOpenProject, FakeGitHub]:
        op = FakeOpenProject()
        task = op.add_wp(subject="x", type_name="Task")
        gh = FakeGitHub()
        # Seed a branch + PR via the usual path
        gh.branches["aidlc/x"] = "headsha1"
        pr = gh.open_pull_request(title="t", body="b", head="aidlc/x", base="main")
        db.upsert_snapshot(
            db.StatusSnapshot(
                work_package_id=task.id,
                wp_status="New",
                pr_number=pr.number,
                pr_state="open",
                ci_conclusion=None,
            )
        )
        return op, gh

    def test_noop_when_nothing_changed(self) -> None:
        op, gh = self._setup_open_pr()
        gh.ci_by_sha["headsha1"] = None
        changes = run_status_updates(op=op, gh=gh)
        assert len(changes) == 1
        assert changes[0].transition == "no_change"

    def test_ci_failure_leaves_comment(self) -> None:
        op, gh = self._setup_open_pr()
        gh.ci_by_sha["headsha1"] = "failure"
        changes = run_status_updates(op=op, gh=gh)
        assert changes[0].transition == "ci_failed"
        assert any("CI failed" in body for _, body in op.comments)

    def test_merged_pr_moves_wp_to_done(self) -> None:
        op, gh = self._setup_open_pr()
        # simulate merge
        pr = next(iter(gh.prs.values()))
        pr.state = "closed"
        pr.merged = True
        gh.ci_by_sha["headsha1"] = "success"
        changes = run_status_updates(op=op, gh=gh)
        assert changes[0].transition == "merged"
        assert changes[0].new_status == "Closed"

    def test_ci_success_transitions_to_in_review(self) -> None:
        op, gh = self._setup_open_pr()
        gh.ci_by_sha["headsha1"] = "success"
        changes = run_status_updates(op=op, gh=gh)
        assert changes[0].transition == "ci_passed"
        assert changes[0].new_status == "In review"
