"""Unit tests for the Claude Code subprocess adapter.

We stub the `claude` binary with a tiny shell script so the tests run
without needing Claude Code installed.
"""

from __future__ import annotations

import os
import stat
from pathlib import Path

import pytest

from aidlc.coding_agents import ClaudeCodeAgent


def _write_fake_claude(
    tmp_path: Path,
    *,
    stdout: str = '{"result": "did the thing", "num_turns": 3, "total_cost_usd": 0.05}',
    exit_code: int = 0,
    touch_file: str | None = "generated.py",
) -> Path:
    """Drop a shell script at tmp_path/claude that mimics `claude -p`."""
    script = tmp_path / "claude"
    touch_line = f'echo "# generated by fake claude" > "$PWD/{touch_file}"' if touch_file else ""
    script.write_text(f"#!/bin/sh\n{touch_line}\ncat <<'EOF'\n{stdout}\nEOF\nexit {exit_code}\n")
    script.chmod(script.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)
    return script


class TestClaudeCodeAgent:
    def test_returns_result_on_happy_path(self, tmp_path: Path) -> None:
        claude_bin = _write_fake_claude(tmp_path)
        workdir = tmp_path / "workdir"
        workdir.mkdir()

        agent = ClaudeCodeAgent(bin_path=str(claude_bin))
        r = agent.implement(prompt="do a thing", workdir=workdir)

        assert r.summary == "did the thing"
        assert r.turns == 3
        assert r.cost_usd == pytest.approx(0.05)
        assert (workdir / "generated.py").exists()

    def test_surfaces_claude_error_exit(self, tmp_path: Path) -> None:
        claude_bin = _write_fake_claude(tmp_path, stdout="boom", exit_code=2)
        workdir = tmp_path / "workdir"
        workdir.mkdir()

        agent = ClaudeCodeAgent(bin_path=str(claude_bin))
        with pytest.raises(RuntimeError, match="claude exited 2"):
            agent.implement(prompt="x", workdir=workdir)

    def test_raises_if_binary_missing(self, tmp_path: Path) -> None:
        workdir = tmp_path / "workdir"
        workdir.mkdir()
        agent = ClaudeCodeAgent(bin_path=str(tmp_path / "does-not-exist"))
        with pytest.raises(RuntimeError, match="not found on PATH"):
            agent.implement(prompt="x", workdir=workdir)

    def test_raises_if_workdir_missing(self, tmp_path: Path) -> None:
        claude_bin = _write_fake_claude(tmp_path)
        agent = ClaudeCodeAgent(bin_path=str(claude_bin))
        with pytest.raises(FileNotFoundError):
            agent.implement(prompt="x", workdir=tmp_path / "nope")

    def test_is_error_in_payload_becomes_runtime_error(self, tmp_path: Path) -> None:
        claude_bin = _write_fake_claude(
            tmp_path,
            stdout='{"result": "hit budget cap", "is_error": true}',
        )
        workdir = tmp_path / "workdir"
        workdir.mkdir()
        agent = ClaudeCodeAgent(bin_path=str(claude_bin))
        with pytest.raises(RuntimeError, match="hit budget cap"):
            agent.implement(prompt="x", workdir=workdir)

    def test_builds_expected_argv(self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
        """The adapter must pass --permission-mode and --max-turns through."""
        captured: list[str] = []

        def fake_run(cmd: list[str], **_: object) -> object:
            captured.extend(cmd)

            class R:
                returncode = 0
                stdout = '{"result": "ok"}'
                stderr = ""

            return R()

        monkeypatch.setattr("subprocess.run", fake_run)
        workdir = tmp_path / "workdir"
        workdir.mkdir()

        agent = ClaudeCodeAgent(
            bin_path="claude",
            permission_mode="acceptEdits",
            max_turns=7,
        )
        agent.implement(prompt="hello", workdir=workdir)

        assert "--permission-mode" in captured
        assert "acceptEdits" in captured
        assert "--max-turns" in captured
        assert "7" in captured
        assert "-p" in captured
        assert "hello" in captured
        # sanity — env wasn't leaked
        assert os.environ.get("CLAUDE_CODE_SSE_PORT") is None
