"""Stage 1 — Idea → Spec.

Given a raw feature-idea work package, produce a structured spec and write
it back to the work package's description. Also transitions the ticket to
a "Specified" status if one exists.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Any

from aidlc import db
from aidlc.llm import LLMProviderIface, extract_json
from aidlc.logging import get_logger
from aidlc.openproject import OpenProjectClient
from aidlc.prompts import render

log = get_logger(__name__)


# Candidate status names we'll try to transition to, in order of preference.
# Left flexible because OpenProject admins often rename these.
SPEC_READY_STATUSES = ["Specified", "In specification", "Ready for dev", "Confirmed"]


@dataclass
class IdeaToSpecResult:
    work_package_id: int
    spec: dict[str, Any]
    markdown: str
    transitioned_to: str | None


def _spec_to_markdown(spec: dict[str, Any]) -> str:
    """Render the JSON spec as a tidy markdown block for the ticket body."""
    lines: list[str] = ["## Spec (generated by AI-DLC)", ""]
    lines.append(f"**Summary:** {spec.get('summary', '').strip()}")
    lines.append("")
    lines.append(f"**User story:** {spec.get('user_story', '').strip()}")
    lines.append("")

    def _bullets(title: str, key: str) -> None:
        items = spec.get(key) or []
        if not items:
            return
        lines.append(f"### {title}")
        for item in items:
            lines.append(f"- {item}")
        lines.append("")

    _bullets("Acceptance criteria", "acceptance_criteria")
    _bullets("Out of scope", "out_of_scope")
    _bullets("Risks", "risks")
    _bullets("Open questions", "open_questions")

    size = spec.get("rough_size")
    if size:
        lines.append(f"**Rough size:** {size}")
        lines.append("")
    lines.append("_This spec was drafted by an AI agent. A human must review before scheduling._")
    return "\n".join(lines)


def run_idea_to_spec(
    *,
    llm: LLMProviderIface,
    op: OpenProjectClient,
    work_package_id: int,
    force: bool = False,
) -> IdeaToSpecResult:
    """Draft a spec for ``work_package_id`` and patch it back into OpenProject."""
    if not force and db.has_run("idea_to_spec", work_package_id):
        log.info("idea_to_spec.skip_already_run", wp=work_package_id)
        wp = op.get_work_package(work_package_id)
        return IdeaToSpecResult(
            work_package_id=wp.id,
            spec={},
            markdown=wp.description_text or "",
            transitioned_to=None,
        )

    wp = op.get_work_package(work_package_id)
    log.info("idea_to_spec.start", wp=wp.id, subject=wp.subject)

    prompt = render(
        "idea_to_spec",
        subject=wp.subject,
        description=(wp.description_text or "").strip() or "(no description provided)",
    )
    raw = llm.complete(system="You produce rigorous product specifications.", user=prompt)
    try:
        spec = extract_json(raw)
    except ValueError:
        db.record_run(
            stage="idea_to_spec",
            work_package_id=wp.id,
            status="error",
            notes=f"Could not parse LLM output:\n{raw[:1000]}",
        )
        raise

    markdown = _spec_to_markdown(spec)

    # Preserve any existing description content under a separator.
    original = (wp.description_text or "").strip()
    new_description = markdown
    if original and not original.startswith("## Spec"):
        new_description = f"{markdown}\n\n---\n\n## Original idea\n\n{original}"

    updated = op.update_work_package(wp, description=new_description)

    transitioned_to: str | None = None
    for name in SPEC_READY_STATUSES:
        status = op.find_status_by_name(name)
        if status is not None:
            op.update_work_package(updated, status_id=status.id)
            transitioned_to = status.name
            break
    if transitioned_to is None:
        log.warning("idea_to_spec.no_spec_status", tried=SPEC_READY_STATUSES)

    op.add_comment(
        wp.id,
        "AI-DLC drafted a spec from the original idea and updated the description. "
        f"Size estimate: **{spec.get('rough_size', 'unknown')}**. "
        "Please review acceptance criteria and open questions.",
    )

    db.record_run(
        stage="idea_to_spec",
        work_package_id=wp.id,
        status="ok",
        notes=json.dumps({"transitioned_to": transitioned_to})[:500],
    )
    log.info("idea_to_spec.done", wp=wp.id, transitioned_to=transitioned_to)
    return IdeaToSpecResult(
        work_package_id=wp.id,
        spec=spec,
        markdown=markdown,
        transitioned_to=transitioned_to,
    )
