"""Stage 2 — Spec → Tasks.

Given a spec'd work package (produced by stage 1), ask the LLM to
decompose it into child tasks and create them as children of the parent
work package in OpenProject.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from typing import Any

from aidlc import db
from aidlc.llm import LLMProviderIface, extract_json
from aidlc.logging import get_logger
from aidlc.openproject import OpenProjectClient
from aidlc.prompts import render

log = get_logger(__name__)

# Fallback when the LLM suggests a type name OpenProject doesn't have.
DEFAULT_CHILD_TYPE = "Task"

_SPEC_BLOCK_RE = re.compile(r"## Spec \(generated by AI-DLC\)(.*?)(?:\n---\n|\Z)", re.DOTALL)


@dataclass
class SpecToTasksResult:
    parent_work_package_id: int
    created_task_ids: list[int]
    shared_context: str = ""


def _parse_spec_from_description(description: str | None) -> dict[str, Any]:
    """Pull what we can out of the markdown spec written by stage 1.

    We treat the spec as semi-structured text — we extract acceptance
    criteria, risks, etc. into a dict that gets passed to the LLM. We
    do NOT require an exact round-trip — the LLM gets the full markdown
    too.
    """
    description = description or ""
    match = _SPEC_BLOCK_RE.search(description)
    spec_text = match.group(1) if match else description

    def _extract_bullets(heading: str) -> list[str]:
        pattern = rf"### {heading}\s*\n(.*?)(?:\n###|\n##|\Z)"
        m = re.search(pattern, spec_text, re.DOTALL | re.IGNORECASE)
        if not m:
            return []
        return [
            line.lstrip("- ").strip()
            for line in m.group(1).splitlines()
            if line.strip().startswith("-")
        ]

    return {
        "acceptance_criteria": _extract_bullets("Acceptance criteria"),
        "risks": _extract_bullets("Risks"),
        "open_questions": _extract_bullets("Open questions"),
        "full_markdown": spec_text.strip(),
    }


def _resolve_type_id(op: OpenProjectClient, requested: str) -> int:
    t = op.find_type_by_name(requested) or op.find_type_by_name(DEFAULT_CHILD_TYPE)
    if t is None:
        types = op.list_types()
        if not types:
            raise RuntimeError("OpenProject returned no work-package types")
        return types[0].id
    return t.id


def run_spec_to_tasks(
    *,
    llm: LLMProviderIface,
    op: OpenProjectClient,
    parent_work_package_id: int,
    project_identifier: str,
    force: bool = False,
) -> SpecToTasksResult:
    if not force and db.has_run("spec_to_tasks", parent_work_package_id):
        log.info("spec_to_tasks.skip_already_run", wp=parent_work_package_id)
        return SpecToTasksResult(
            parent_work_package_id=parent_work_package_id,
            created_task_ids=[],
        )

    parent = op.get_work_package(parent_work_package_id)
    spec = _parse_spec_from_description(parent.description_text)
    log.info("spec_to_tasks.start", parent=parent.id, criteria=len(spec["acceptance_criteria"]))

    prompt = render("spec_to_tasks", subject=parent.subject, spec_json=json.dumps(spec, indent=2))
    raw = llm.complete(
        system="You are a tech lead who decomposes specs into engineering tasks.",
        user=prompt,
        max_tokens=3000,
    )
    try:
        parsed = extract_json(raw)
    except ValueError:
        db.record_run(
            stage="spec_to_tasks",
            work_package_id=parent.id,
            status="error",
            notes=f"Unparseable LLM output:\n{raw[:1000]}",
        )
        raise

    # Accept both the new {shared_context, tasks} format and the legacy [tasks] array.
    shared_context = ""
    if isinstance(parsed, dict) and "tasks" in parsed:
        shared_context = str(parsed.get("shared_context", ""))
        tasks = parsed["tasks"]
    elif isinstance(parsed, list):
        tasks = parsed
    else:
        raise ValueError(
            f"Expected JSON object with 'tasks' or a JSON array, got {type(parsed).__name__}"
        )

    if not isinstance(tasks, list):
        raise ValueError(f"Expected tasks to be a list, got {type(tasks).__name__}")

    created_ids: list[int] = []
    for idx, task in enumerate(tasks):
        subject = str(task.get("subject", "")).strip()
        if not subject:
            log.warning("spec_to_tasks.skip_task_no_subject", index=idx)
            continue
        description = str(task.get("description", "")).strip()
        type_name = str(task.get("type") or DEFAULT_CHILD_TYPE)
        type_id = _resolve_type_id(op, type_name)
        depends_on = task.get("depends_on_index") or []
        if depends_on:
            description += "\n\n**Depends on:** " + ", ".join(
                f"task #{i + 1} ({tasks[i].get('subject', '?')})"
                for i in depends_on
                if isinstance(i, int) and 0 <= i < len(tasks)
            )
        child = op.create_work_package(
            project_identifier=project_identifier,
            subject=subject,
            description=description or "(no description supplied)",
            type_id=type_id,
            parent_id=parent.id,
        )
        created_ids.append(child.id)
        log.info("spec_to_tasks.child_created", parent=parent.id, child=child.id, subject=subject)

    op.add_comment(
        parent.id,
        f"AI-DLC created **{len(created_ids)} child tasks** from this spec. "
        "Review and prioritise before assigning.",
    )

    db.record_run(
        stage="spec_to_tasks",
        work_package_id=parent.id,
        status="ok",
        notes=json.dumps({"child_ids": created_ids, "shared_context": shared_context})[:2000],
    )
    log.info("spec_to_tasks.done", parent=parent.id, created=len(created_ids))
    return SpecToTasksResult(
        parent_work_package_id=parent.id,
        created_task_ids=created_ids,
        shared_context=shared_context,
    )
